name: Django CI

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

env:
  SECRET_KEY: yoursecretkey
  DEBUG: True
  DATABASE_NAME: food
  DATABASE_USER: bob
  DATABASE_PASS: pass1234!
  DATABASE_HOST: localhost

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          DATABASE_NAME: $DATABASE_NAME
          DATABASE_USER: $DATABASE_USER
          DATABASE_PASS: $DATABASE_PASS
          DATABASE_HOST: $DATABASE_HOST
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install PostgreSQL client
      run: |
        sudo apt-get update
        sudo apt-get install --yes postgresql-client
    - name: Test database connection
      run: psql -h postgres -d postgres_db -U postgres_user -c 'SELECT 1;'
      env:
        PGPASSWORD: postgres_password
    - name: Run migrations
      run: |
        python manage.py makemigrations
        python manage.py migrate
    - name: Lint with flake8
      run: |
        flake8
    - name: Run Tests
      run: |
        python manage.py test